### ISSUE TITLE
Error when processing function argument's annotations

### ISSUE THREAD

**Issue by JarryShaw** [netromdk/vermin#40]
**Describe the bug**

When trying to test the minimum version of my new project, the error as attached below occurred.

After some tests, as I would understand, this is due to the detection of the `Literal` annotation in `vermin.source_visitor.__handle_FunctionDef`, when the annotation of function arguments are used in form of `typing.xxx`.

**To Reproduce**
Steps to reproduce the behavior.

```python
# error-haunted code
import typing

def foo(arg1: typing.Union[str, int], arg2: typing.Literal['bar'], arg3: typing.Optional[bool]):
    pass

# AttributeError: 'Attribute' object has no attribute 'id'
```

Each argument's annotation as in the above function will  eventually reproduce the error. However, if you do the other way round, `vermin` will be able to handle:

```python
# successful code
from typing import Union, Literal, Optional

def foo(arg1: Union[str, int], arg2: Literal['bar'], arg3: Optional[bool]):
    pass

# Minimum required versions: 3.8
# Incompatible versions:     2
```

**Expected behavior**

The processing of function argument's annotations should not raise any error :)

**Environment (please complete the following information):**
 - Vermin version or Git commit: v0.10.0

**Additional context**

Below is the complete traceback from the error.

```pytb
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/profile/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/project/.venv/lib/python3.8/site-packages/vermin/processor.py", line 59, in process_individual
    visitor.tour(res.node)
  File "/project/.venv/lib/python3.8/site-packages/vermin/source_visitor.py", line 707, in tour
    self.visit(node)
  File "/profile/.pyenv/versions/3.8.0/lib/python3.8/ast.py", line 360, in visit
    return visitor(node)
  File "/project/.venv/lib/python3.8/site-packages/vermin/source_visitor.py", line 716, in generic_visit
    super(SourceVisitor, self).generic_visit(node)
  File "/profile/.pyenv/versions/3.8.0/lib/python3.8/ast.py", line 368, in generic_visit
    self.visit(item)
  File "/profile/.pyenv/versions/3.8.0/lib/python3.8/ast.py", line 360, in visit
    return visitor(node)
  File "/project/.venv/lib/python3.8/site-packages/vermin/source_visitor.py", line 1261, in visit_FunctionDef
    if self.__handle_FunctionDef(node):
  File "/project/.venv/lib/python3.8/site-packages/vermin/source_visitor.py", line 1237, in __handle_FunctionDef
    self.generic_visit(node)
  File "/project/.venv/lib/python3.8/site-packages/vermin/source_visitor.py", line 716, in generic_visit
    super(SourceVisitor, self).generic_visit(node)
  File "/profile/.pyenv/versions/3.8.0/lib/python3.8/ast.py", line 368, in generic_visit
    self.visit(item)
  File "/profile/.pyenv/versions/3.8.0/lib/python3.8/ast.py", line 360, in visit
    return visitor(node)
  File "/project/.venv/lib/python3.8/site-packages/vermin/source_visitor.py", line 1261, in visit_FunctionDef
    if self.__handle_FunctionDef(node):
  File "/project/.venv/lib/python3.8/site-packages/vermin/source_visitor.py", line 1253, in __handle_FunctionDef
    (isinstance(ann, ast.Subscript) and ann.value.id == "Literal"):
AttributeError: 'Attribute' object has no attribute 'id'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/project/.venv/bin/vermin", line 8, in <module>
    sys.exit(main())
  File "/project/.venv/lib/python3.8/site-packages/vermin/main.py", line 44, in main
    (mins, incomp, unique_versions, backports) = processor.process(paths, processes)
  File "/project/.venv/lib/python3.8/site-packages/vermin/processor.py", line 88, in process
    for proc_res in pool.imap(process_individual, ((path, config) for path in paths)):
  File "/profile/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/pool.py", line 865, in next
    raise value
AttributeError: 'Attribute' object has no attribute 'id'
```

FYI, the variable's values are as following:

* `ann = <_ast.Subscript object>`
* `ann.value = <_ast.Attribute object>`
* `ann.value.value = <_ast.Name object>`
* `ann.value.value.id = 'typing'`
* `ann.value.attr = 'xxx'`  (the name from `typing` module)

**Comment by netromdk** [comment]
Thanks for reporting, @JarryShaw! Will look into it.

**Comment by netromdk** [comment]
It's been fixed.
